using UnityEditor;

namespace MirrorTrial.Editor.Level
{
    [InitializeOnLoad]
    static class Level01AutoRun
    {
        const string SessionKey = "MirrorTrial.Level01.AutoGenerated.v2";

        static Level01AutoRun()
        {
            EditorApplication.delayCall += GenerateOnce;
        }

        static void GenerateOnce()
        {
            if (SessionState.GetBool(SessionKey, false))
                return;

            SessionState.SetBool(SessionKey, true);
            Level01Setup.Generate();
        }
    }
}
